# Generated by Django 4.1 on 2022-08-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True, verbose_name='Linea')),
                ('image', models.FileField(blank=True, null=True, upload_to='core/linea', verbose_name='Foto')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
