# Generated by Django 4.1 on 2022-08-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_grupo_linea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='linea',
        ),
        migrations.AddField(
            model_name='grupo',
            name='linea',
            field=models.ManyToManyField(to='core.linea'),
        ),
    ]
